### ISSUE TITLE
cmake dependency

### ISSUE THREAD

**Issue by markclaire1** [Nicholaswogan/PhotochemPy#1]
Hi Nick - getting around to the start of the summer plan to begin merging our repos, with an aim towards getting the covde in with some of our updates to templating and isotopes.

I refreshed my fork of PhotochemPy and went for a clean install, and wanted to report that the ~/src/dependencies/compile.sh crashed out of the box as I dont have cmake installed.  I'm happy to go grab it from homebrew, so just a note for the next time you update documentation, to note this as a requirement. I'm not sure if Annaconda does this (your rec), but I generally just use homebrew to pull what I need.

**Comment by markclaire1** [comment]
couple of other quick notes from a long slow (and often interupted) day of updating/installing/playing around.
In addition to 'brew install cmake', I also had to 'python -m pip install pathos'

Those two most users should be able to figure out, but I also had another slightly more tricky one.

One of the libraries invoked was insistant on trying to find /usr/local/opt/gcc/lib/gcc/10/something but my systems had the files in ~/11/  To fix, I had to navigate to the offending location and make a symbolic link 'ln -s 11 10' which I think might be too much for some users to grok.   That said, I'm not sure if the error came from trying to import Photochem.py from the root directory versus launching python from the PhotochemPy subdirectory.  Do you need to start there? - if so, might be something to update the documention on when you have a moment.

one final note - I'm sure you've seen this too, but I get deprecation notice from pip on primary install, something about building in place vs. temp dirs.

But (in addition to finally getting around to a Big Sur upgrade, etc.) I did get some CVODE runs going.  Exciting stuff, and I look forward to digging in more over the next few months.

**Comment by Nicholaswogan** [comment]
Thanks so much for these notes Mark! 

> One of the libraries invoked was insistant on trying to find /usr/local/opt/gcc/lib/gcc/10/something but my systems had the files in ~/11/ To fix, I had to navigate to the offending location and make a symbolic link 'ln -s 11 10'

**Comment by Nicholaswogan** [comment]
Thanks so much for these notes Mark! I will update the documentation and install scripts to deal with these issues. I should be able to use make the setup.py automatically install these dependencies... Question:

> One of the libraries invoked was insistant on trying to find /usr/local/opt/gcc/lib/gcc/10/something but my systems had the files in ~/11/ To fix, I had to navigate to the offending location and make a symbolic link 'ln -s 11 10' 

Was this before or after you upgraded to Big Sur? 

> That said, I'm not sure if the error came from trying to import Photochem.py from the root directory versus launching python from the PhotochemPy subdirectory. Do you need to start there? 

If you did `pip install .`, then the compiled code, the python scripts, and the `data` folder (contains xsections and other stuff) will be installed to your list of python packages, so you can run the code from any directory on your computer. With this approach you will still need input files (the files in `input/templates`). 

Alternatively you can do `./compile.sh` from the root directory. This will compile the code in the root directory, and the code will work only if a python script is in the root directory.

**Comment by markclaire1** [comment]
Yeah - you can strike the gcc comment. Some libraries just got confused in the order of which I upgraded the OS/homebrew/command-line-tools.  All is well now.

On the original, simplier theme of the thread, you could also include a recomendation (and/or dependency) on the python ruamel.yaml packgage

**Comment by Nicholaswogan** [comment]
Docs are updated, and other Python dependencies should be installed via setup.py: 9e132f8ed265afbb813e49acbe2e293382b8f7d8
