### ISSUE TITLE
Installation Issue with setup.py on Ubuntu 22.04

### ISSUE THREAD

**Issue by janetteng123** [Nicholaswogan/PhotochemPy#3]
[error.txt](https://github.com/Nicholaswogan/PhotochemPy/files/11900724/error.txt)

**The file above shows the error when installing setup.py on Ubuntu. I followed the installation instructions from README. However, when I tried running python setup.py install, I got an error. It's also shown below here:**

(photochempy) janet@janet-VirtualBox:~/Desktop/PhotochemPy$ python setup.py install

/home/janet/anaconda3/envs/photochempy/lib/python3.10/site-packages/setuptools/dist.py:745: SetuptoolsDeprecationWarning: Invalid dash-separated options

!!

        ********************************************************************************

        Usage of dash-separated 'description-file' will not be supported in future

        versions. Please use the underscore name 'description_file' instead.

        By 2023-Sep-26, you need to update your project and remove deprecated calls

        or your builds will no longer be supported.

        See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.

        ********************************************************************************

!!

  opt = self.warn_dash_deprecation(opt, section)

/home/janet/anaconda3/envs/photochempy/lib/python3.10/site-packages/setuptools/config/setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg`

!!

        ********************************************************************************

        The license_file parameter is deprecated, use license_files instead.

        By 2023-Oct-30, you need to update your project and remove deprecated calls

        or your builds will no longer be supported.

        See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.

        ********************************************************************************

!!

  parsed = self.parsers.get(option_name, lambda x: x)(value)

Traceback (most recent call last):

  File "/home/janet/Desktop/PhotochemPy/setup.py", line 8, in <module>

    setup(

  File "/home/janet/anaconda3/envs/photochempy/lib/python3.10/site-packages/skbuild/setuptools_wrap.py", line 488, in setup

    ) = _parse_setuptools_arguments(kw)

  File "/home/janet/anaconda3/envs/photochempy/lib/python3.10/site-packages/skbuild/setuptools_wrap.py", line 221, in _parse_setuptools_arguments

    dist.parse_config_files()

  File "/home/janet/anaconda3/envs/photochempy/lib/python3.10/site-packages/setuptools/dist.py", line 898, in parse_config_files

    pyprojecttoml.apply_configuration(self, filename, ignore_option_errors)

  File "/home/janet/anaconda3/envs/photochempy/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 66, in apply_configuration

    config = read_configuration(filepath, True, ignore_option_errors, dist)

  File "/home/janet/anaconda3/envs/photochempy/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 128, in read_configuration

    validate(subset, filepath)

  File "/home/janet/anaconda3/envs/photochempy/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 55, in validate

    raise ValueError(f"{error}\n{summary}") from None

ValueError: invalid pyproject.toml config: `project`.

configuration error: `project` must contain ['name'] properties

**Comment by Nicholaswogan** [comment]
Can you do `conda list` in your `photochempy` conda environment, and post the output

**Comment by janetteng123** [comment]
I have attached the output after doing `conda list` in my `photochempy `conda environment

[conda list.txt](https://github.com/Nicholaswogan/PhotochemPy/files/11908326/conda.list.txt)

**Comment by Nicholaswogan** [comment]
Fixed with f1d5e654d67dfee405cb75bb3848aef0bacea479 . Let me know if it works. Note that you may need to install cmake with `conda install -c conda-forge cmake ninja`.

**Comment by janetteng123** [comment]
I updated my file and installed cmake, but I'm getting the following error:
[error.2.txt](https://github.com/Nicholaswogan/PhotochemPy/files/11909237/error.2.txt)

**Comment by janetteng123** [comment]
I think it worked! I was able to install it. Thank you!
